### PR TITLE
[20240816] 맹인호_13회차 문제 풀이 7주차

### PR DESCRIPTION
**Pull request by MaengSung**
설탕 배달 : https://www.acmicpc.net/problem/2839
pascals-triangle : https://leetcode.com/problems/pascals-triangle/description/
climbing-stairs : https://leetcode.com/problems/climbing-stairs/description/
pascals-triangle || : https://leetcode.com/problems/pascals-triangle-ii/description/
Best Time to Buy and Sell Stock : https://leetcode.com/problems/best-time-to-buy-and-sell-stock/
타겟 넘버 : https://school.programmers.co.kr/learn/courses/30/lessons/42895
N으로 표현 : https://school.programmers.co.kr/learn/courses/30/lessons/42895
정수삼각형 : https://school.programmers.co.kr/learn/courses/30/lessons/43105

### CODE REVIEW

**Comment by koosco** [comment]
pascals triangle
```
class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        dp = [[1] for _ in range(numRows)]
        for i in range(1, numRows):
            for j in range(1, i):
                dp[i].append(dp[i-1][j-1] + dp[i-1][j])
            dp[i].append(1)
        return dp
        

```

**Comment by koosco** [comment]
Best Time to Buy and Sell Stock
```
from typing import List


class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        min_v = prices[0]
        res = 0
        for i in range(1, len(prices)):
            x = max(0, prices[i] - min_v)
            res = x if not res else max(res, x)
            min_v = min(min_v, prices[i])
        return res

```

**Comment by koosco** [comment]
climbing-stairs
```
class Solution:
    def climbStairs(self, n: int) -> int:
        if n <= 2:
            return n
        else:
            pp, p = 1, 2
            for i in range(3, n + 1):
                c = pp + p
                pp, p = p, c
            return c
```

**Comment by koosco** [comment]
타겟 넘버
```
def solution(numbers, target):
    def dfs(s, depth=1):
        nonlocal res
        if depth == len(numbers):
            if s == target:
                res += 1
            return
        dfs(s + numbers[depth], depth + 1)
        dfs(s - numbers[depth], depth + 1)
    res = 0
    dfs(numbers[0])
    dfs(-numbers[0])
    return res
```

**Comment by koosco** [comment]
N으로 표현
```
def solution(N: int, number: int):
    answer = -1
    dp = [set() for _ in range(9)]
    for i in range(1, 9):
        dp[i].add(int(str(N) * i))
        for j in range(i):
            for x in dp[j]:
                for y in dp[i-j]:
                    dp[i].add(x + y)
                    dp[i].add(x - y)
                    dp[i].add(x * y)
                    if y: dp[i].add(x // y)
        if number in dp[i]:
            answer = i
            break
    return answer
```

**Comment by koosco** [comment]
정수 삼각형
```
from typing import List


def solution(triangle: List[List[int]]):
    n = len(triangle)
    dp = [[0] * n for _ in range(n)]
    dp[0][0] = triangle[0][0]
    for i in range(1, n):
        for j in range(len(triangle[i])):
            if j == 0:
                dp[i][j] = triangle[i][j] + dp[i-1][j]
            elif j == i:
                dp[i][j] = triangle[i][j] + dp[i-1][j-1]
            else:
                dp[i][j] = triangle[i][j] + max(dp[i-1][j-1], dp[i-1][j])
    return max(dp[-1])
```

**Comment by wooyong99** [comment]
설탕배달
```java
import java.util.Scanner;

public class Main {
    
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        int sugar = sc.nextInt();

        int count = 0;

        while(sugar > 0) {
            if(sugar % 5 == 0) {
                count += sugar / 5;
                System.out.println(count);
                return ;
            }
            if(sugar < 3) {
                System.out.println(-1);
                return ;
            }
            sugar-=3;
            count++;
        }
        System.out.println(count);        
    }
}
출처: [https://tweety1121.tistory.com/entry/백준-2839번-설탕배달-자바-풀이](https://tweety1121.tistory.com/entry/%EB%B0%B1%EC%A4%80-2839%EB%B2%88-%EC%84%A4%ED%83%95%EB%B0%B0%EB%8B%AC-%EC%9E%90%EB%B0%94-%ED%92%80%EC%9D%B4) [Pli's 개발일기:티스토리]
```

**Comment by wooyong99** [comment]
설탕배달
```java
import java.util.Scanner;

public class Main {
    
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        int sugar = sc.nextInt();

        int count = 0;
        while(sugar > 0) {
            if(sugar % 5 == 0) {
                count += sugar / 5;
                System.out.println(count);
                return ;
            }
            if(sugar < 3) {
                System.out.println(-1);
                return ;
            }
            sugar-=3;
            count++;
        }
        System.out.println(count);
    }
}
```

**Comment by wooyong99** [comment]
n으로 표현
```java
import java.util.*; 

class Solution {
    public int solution(int N, int number) {
        List<Set<Integer>> setList = new ArrayList<>();
        for(int i = 0; i <= 8; i++) {
            setList.add(new HashSet<>());
        }
        // 1회
        setList.get(1).add(N);

        StringBuilder sb = new StringBuilder();
        sb.append(N);

        // 2회 이상
        for(int i = 2; i < setList.size(); i++) {
            sb.append(N);
            Set<Integer> newSet = setList.get(i);
            newSet.add(Integer.parseInt(sb.toString()));

            for(int j = 1; j <= i; j++) {
                Set<Integer> setA = setList.get(j);
                Set<Integer> setB = setList.get(i - j);

                for (Integer numA : setA) {
                    for (Integer numB : setB) {
                        newSet.add(numA + numB);
                        newSet.add(numA - numB);
                        newSet.add(numA * numB);
                        if(numA != 0 && numB != 0) {
                            newSet.add(numA / numB);
                        }
                    }
                }
            }
        }
        
        for (Set<Integer> set : setList) {
            if(set.contains(number)) {
                return setList.indexOf(set);
            }
            
        }
        return -1;
    }
}
```

**Comment by wooyong99** [comment]
정수삼각형
```java
import java.util.*;

class Solution {
    public int solution(int[][] triangle) {
        int answer = 0;
        
        // 배열 깊은 복사
        int[][] tree = new int[triangle.length][];
        
        for(int i = 0 ; i < triangle.length; i++){
            tree[i] = triangle[i].clone();
        }
        
        for(int i = 0; i< tree.length-1; i++){
            for(int j = 0;j<tree[i].length; j++){
                tree[i+1][j] = Math.max(tree[i][j] + triangle[i+1][j], tree[i+1][j]);
                tree[i+1][j+1] = Math.max(tree[i][j] + triangle[i+1][j+1], tree[i+1][j+1]);
            }
        }
        
        for(int i = 0 ; i < tree[tree.length-1].length; i++){
            answer = Math.max(answer,tree[tree.length-1][i]);
        }

        return answer;
    }
}
```

**Pull request merged**
