### PR TITLE
[20240729] 구태형_8회차 문제 풀이 5주차 

### PR DESCRIPTION
**Pull request by koosco**
tree/trie
1967 트리의지름 : https://www.acmicpc.net/problem/1967
5052 전화번호 목록 : https://www.acmicpc.net/problem/5052
5639 이진 검색 트리 : https://www.acmicpc.net/problem/5639
7432 디스크트리 : https://www.acmicpc.net/problem/7432
9372 상근이의 여행 : https://www.acmicpc.net/problem/9372
14725 개미굴 : https://www.acmicpc.net/problem/14725

backtracking
14888 연산자 끼워넣기 : https://www.acmicpc.net/problem/14888
6603 로또 : https://www.acmicpc.net/problem/6603
15657 N과 M(8) : https://www.acmicpc.net/problem/15657
15655 N과 M(6) : https://www.acmicpc.net/problem/15655
15654 N과 M(5) : https://www.acmicpc.net/problem/15654
15652 N과 M(4) : https://www.acmicpc.net/problem/15652
15651 N과 M(3) : https://www.acmicpc.net/problem/15651
15650 N과 M(2) : https://www.acmicpc.net/problem/15650
15649 N과 M(1) : https://www.acmicpc.net/problem/15649

### CODE REVIEW

**Comment by MaengSung** [comment]
S2_6603

 import sys
import itertools

read = sys.stdin.readline
result = []

while True:
    line = list(map(int,read().rstrip().split()))
    n = line.pop(0)
    if n == 0:
        break
    r = itertools.combinations(line,6)
    result.append(r)

for i in result:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()


import sys

read = sys.stdin.readline

result = []
def dfs(s,t):
    if len(t) == 6:
        line.append(t)
        return
    for i in range(len(s)):
        dfs(s[i+1:],t+[s[i]])

while True:
    s = list(map(int, read().rstrip().split()))
    k = s[0]
    if k == 0:
        break
    line = []
    dfs(s[1:],[])
    result.append(line)

for i in result:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

**Comment by wooyong99** [comment]
S1_14888
```java
import java.util.*;
import java.io.*;

public class Main{
    public static int n,k;
    public static int[] arr;
    public static ArrayList<String> exp ;
    public static ArrayList<Integer> list = new ArrayList();
    public static int max = -1_000_000_000;
    public static int min = 1_000_000_000;
    public static void main(String[] args) throws IOException{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        n = Integer.parseInt(br.readLine());
        StringTokenizer st = new StringTokenizer(br.readLine());
        arr = new int[n];
        exp = new ArrayList<>();


        // n개 수열 배열에 저장
        for(int i = 0 ; i <arr.length; i++){
            arr[i] = Integer.parseInt(st.nextToken());
        }
        // n-1개 수식 저장
        st = new StringTokenizer(br.readLine());
        int plus = Integer.parseInt(st.nextToken());

        for(int i = 0; i< plus; i++){
            exp.add("+");
        }

        int minus = Integer.parseInt(st.nextToken());
        for(int i = 0; i< minus; i++){
            exp.add("-");
        }

        int mul = Integer.parseInt(st.nextToken());
        for(int i = 0; i< mul; i++){
            exp.add("*");
        }

        int div = Integer.parseInt(st.nextToken());
        for(int i = 0; i< div; i++){
            exp.add("/");
        }

        recursive(0);
        System.out.println(max);
        System.out.println(min);
    }
    public static int calc(int a, int b, String ex){
        if(ex.equals("+")){
            return a+b;
        }else if(ex.equals("-")){
            return a-b;
        }else if(ex.equals("*")){
            return a*b;
        }else{
            if(a < 0){
                a = Math.abs(a);
                return (a/b)*-1;
            }
            return (a/b);
        }
    }

    public static void recursive(int depth){
        if(depth == exp.size()){
            int sum =0;
            for(int i = 0 ; i <list.size(); i++){
                if(i == 0){
                    sum = calc(arr[i], arr[i+1], exp.get(list.get(i)));
                }else{
                    sum = calc(sum, arr[i+1], exp.get(list.get(i)));
                }
            }
            if(sum > max){
                max = sum;
            }
            if(sum < min){
                min = sum;
            }
            return;
        }

        for(int i = 0 ; i < exp.size(); i++){
            if(!list.contains(i)){
                list.add(i);
                recursive(depth+1);
                list.remove(list.size()-1);
            }
        }

    }
}
```

**Comment by wooyong99** [comment]
S2_6603
```java
import java.util.*;
import java.io.*;

public class Main{
    public static int k;
    public static int[] arr;
    public static ArrayList<Integer> list = new ArrayList();
    public static StringBuilder sb ;
    public static void main(String[] args) throws IOException{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        String str ="";
        while( !(str = br.readLine()).equals("0")){
            sb=new StringBuilder();
            StringTokenizer st = new StringTokenizer(str);
            k = Integer.parseInt(st.nextToken());
            arr = new int[k];
            for(int i = 0; i<k; i++){
                arr[i] = Integer.parseInt(st.nextToken());
            }
            recursive(0,0);
            System.out.println(sb.toString());
        }
    }


    public static void recursive(int start, int depth){
        if(depth == 6){
            for(int i = 0; i<list.size(); i++){
                sb.append(list.get(i)+" ");
            }
            sb.append("\n");
            return;
        }

        for(int i = start; i<arr.length; i++){
            if(list.size()==0 || !list.contains(arr[i]) && list.get(list.size()-1) < arr[i]){
                list.add(arr[i]);
                recursive(start+1,depth+1);
                list.remove(list.size()-1);
            }
        }
    }
}
```

**Comment by MaengSung** [comment]
## S2_14888

import sys

read = sys.stdin.readline
sys.setrecursionlimit(int(1e6))

n = int(read().rstrip())
line = list(map(int,read().rstrip().split()))
cal = list(map(int,read().rstrip().split()))
result = []

def calculation(s,e,c):
    if c == 0:
        return s+e
    if c == 1:
        return s-e
    if c == 3:
        if s < 0:
            return -((-s)//e)
        return s//e
    if c == 2:
        return s*e

def dfs(arr, total,depth):
    if depth == n-1:
        result.append(total)
        return
    for j in range(4):
        if cal[j]:
            cal[j] -= 1
            dfs(arr[1:],calculation(total,arr[0],j),depth+1)
            cal[j] +=1


dfs(line[1:],line[0],0)
print(max(result))
print(min(result))

**Pull request merged**
